### ISSUE TITLE
Bug regarding GPU loading after packed via bentoml 

### ISSUE THREAD

**Issue by OriAlpha** [bentoml/BentoML#3525]
### Describe the bug

I have transformer model and packed model via bentoml.
I have latest bentoml Version 1.0.13. 

I have used pipeline for creating model and saved model to bento local. 
Just an example: `pipeline('fill-mask', model=model, tokenizer=tokenizer)`

Further i save this model to bentoml local via 
```
bentoml.bentos.build(service="service.py:model_service",include=['service.py'],
                     python=dict(requirements_txt="requirements.txt",))
```

For local testing i have initalized model locally and inference works fine, when i try to serve model it fails giving me CUDA error.

```
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

### Environment

bentoml: 1.0.13
python:3.8
ubuntu:20:04

**Comment by ssheng** [comment]
Thanks for reporting, @OriAlpha. What is the value of the environment variable `CUDA_VISIBLE_DEVICES`?

**Comment by OriAlpha** [comment]
i tried with cuda:0, 0 & 1, all these are same issue

**Comment by aarnphm** [comment]
Hi there, can you send your service definition here?

**Comment by OriAlpha** [comment]
I have added device in the pipeline example
```
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
pipeline(task="text2text-generation", model=model, tokenizer=tokenizer,device=device)
```
Further i call runner for inference
```
runner = bentoml.transformers.get("model:latest").to_runner()
service = bentoml.Service("model", runners=[runner])
@service.api():
runer.run("its an example")
```

**Comment by OriAlpha** [comment]
issue solved in latest version
